namespace: justknife
name: recursive_vars
version: 0.0.2
readme: README.md
repository: https://github.com/justknife/ansible-collection-recursive_vars_loader
authors:
  - justknife
license: MIT
description: Inventory plugin that recursively loads group_vars and host_vars from parent directories
tags: [inventory, plugin, vars, recursive]
dependencies: {}
